import type { Metadata } from "next";
import { Inter, Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import localFont from "next/dist/compiled/@next/font/dist/local";
import React from "react";

const inter = Inter({ subsets: ["latin"] });
const NotoSansKR = Noto_Sans_KR({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ NotoSansKR.className }>{children}</body>
    </html>
  );
}
